<?php

namespace ContainerUdx9CKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\sendPdf' shared autowired service.
     *
     * @return \App\Command\sendPdf
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/sendPdf.php';

        $container->privates['App\\Command\\sendPdf'] = $instance = new \App\Command\sendPdf(($container->services['knp_snappy.pdf'] ?? $container->load('getKnpSnappy_PdfService')));

        $instance->setName('app:sendPdf');
        $instance->setDescription('Read and email and resend the content as a PDF');

        return $instance;
    }
}
