<?php

namespace ContainerUdx9CKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendPdf_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\sendPdf.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\sendPdf.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:sendPdf', [], 'Read and email and resend the content as a PDF', false, #[\Closure(name: 'App\\Command\\sendPdf')] fn (): \App\Command\sendPdf => ($container->privates['App\\Command\\sendPdf'] ?? $container->load('getSendPdfService')));
    }
}
